export const iPhone = [
    {
        id: 0,
        name: "iPhone 11 (Authorised by apple compnay USA)",
        seller: 'T-son',
        img: '',
        price: '',
        Details: "The iPhone 11 is a smartphone from Apple that has a 6.1-inch Liquid Retina HD display",
    },
    {
        id: 1,
        name: "iPhone 11 Pro (Authorised by apple compnay USA)",
        seller: '',
        img: '',
        price: '',
        Details: "The iPhone 11 is a smartphone from Apple that has a 6.1-inch Liquid Retina HD display",
    },
    {
        id: 2,
        name: "iPhone 12 (Authorised by apple compnay USA)",
        seller: '',
        img: '',
        price: '',
        Details: "The iPhone 12 is a smartphone from Apple that has a 6.1-inch Liquid Retina HD display",
    },
    {
        id: 3,
        name: "iPhone 12 Pro (Authorised by apple compnay USA)",
        seller: '',
        img: '',
        price: '',
        Details: "The iPhone 12 is a smartphone from Apple that has a 6.1-inch Liquid Retina HD display",
    },
    {
        id: 4,
        name: "iPhone 13 (Authorised by apple compnay USA)",
        seller: '',
        img: '',
        price: '',
        Details: "The iPhone 13 is a smartphone from Apple that has a 6.1-inch Liquid Retina HD display",
    },
    {
        id: 5,
        name: "iPhone 13 Pro (Authorised by apple compnay USA)",
        seller: '',
        img: '',
        price: '',
        Details: "The iPhone 13 is a smartphone from Apple that has a 6.1-inch Liquid Retina HD display",
    },
    {
        id: 6,
        name: "iPhone 14 (Authorised by apple compnay USA)",
        seller: '',
        img: '',
        price: '',
        Details: "The iPhone 14 is a smartphone from Apple that has a 6.1-inch Liquid Retina HD display",
    },
    {
        id: 7,
        name: "iPhone 14 Pro (Authorised by apple compnay USA)",
        seller: '',
        img: '',
        price: '',
        Details: "The iPhone 14 is a smartphone from Apple that has a 6.1-inch Liquid Retina HD display",
    }
]